language: node_js
node_js:
  - "8"
  - "10"
  - "12"
cache: yarn
install: yarn
before_script:
  - echo Skipping Tests
script:
  - yarn build
  - rm -rf `ls -a | sed "/^dist$/d; /^\.$/d; /^\.\.$/d"`
  - mv dist/* .
after_script:
  - "[ $TRAVIS_NODE_VERSION != 10 ] && exit 1"
  - gem install dpl dpl-pages
  - dpl --provider=pages --github-token=$GITHUB_TOKEN --keep_history --skip_cleanup --target-branch=dist
